language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV="py36--django2.{0,1,2},py36--django3.{0,1,2},syntax"
        - python: 3.7
          env: TOXENV="py37--django2.{0,1,2},py37--django3.{0,1,2}"
        - python: 3.8
          env: TOXENV="py38--django2.{0,1,2},py38--django3.{0,1,2}"
install:
  - pip install tox
script:
  - tox
sudo: false
notifications:
    email: false
